name: Gradle Build

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew setupDecompWorkspace
          ./gradlew build
      - name: List files
        run: ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: phobos-1.3.3
          path: ./build/libs/*release.jar
